"""

Slepc can be tricky to get working. This file, combined with construct.jl, show how we can still make use of MPI to construct the matrices but then return to Arpack to solve the matrices without MPI.

The file construct.jl should be called with 
>>mpiexecjl -n (num_procs) julia examples/NoSlepc/construct.jl

Then this file should be called in serial with
>>julia examples/NoSlepc/solve.jl

Solutions will be written to data/example/

"""

using MID


#set up grids and problem, should be the same as in construct.jl, alternatively grids and problem can be read from file to ensure they are the same.
#see example.jl to see how inputs can be read from file.
N = 100
rgrid = collect(LinRange(0, 1, N));
geo = GeoParamsT(R0=10.0)
prob = init_problem(q=Axel_q, geo=geo); 
grids = init_grids(rgrid=rgrid, mstart=2, mcount=1, nstart=-2, ncount=1);

tae_freq = (0.381 / geo.R0)^2 #previously found tae_freq, solve for eigenvalues near this value.

#solves the matrices generated by construct.jl via Arpack in serial.
solve_from_file(dir="data/example/", grids=grids, R0=geo.R0, σ=tae_freq)


